[package]
name = "typing"
version = "0.1.0"
edition = "2021"

[package.metadata]
path = "src/rust/main.rs"

[dependencies]
wasm-bindgen = { version = "0.2.100", features = ["serde-serialize"] , optional = true}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
js-sys = "0.3"

[[bin]]
name = "typing_bin"
path = "src/rust/main.rs"

[lib]
name = "typing_lib"
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[features]
web = ["wasm-bindgen"]
native = []